config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles
  get "signup", to: "users#new"
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { minimum: 6, maximum: 100}
  validates :description, presence: true, length: { minimum: 10, maximum: 500}
end

app/models/user.rb
class User < ApplicationRecord

  before_save { self.email = email.downcase }
  has_many :articles

  validates :username, presence: true,
   uniqueness: {case_sensitive: false},
   length: {minimum: 3, maximum: 50}

  validates :email, presence: true,
    uniqueness: {case_sensitive: false},
    length: {maximum: 105}

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def show
  end

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)
    @article.user = User.first
    if @article.save
      flash[:notice] = "Article was created successfully"
      redirect_to @article
    else 
      render 'new'
    end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated succesfully"
      redirect_to @article
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end
  
  def article_params
    params.require(:article).permit(:title, :description)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "Welcome to the blog #{@user.username}"
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Your account details got succesfully updated."
      redirect_to articles_path
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:username,:email,:password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj:@article %>

<%= form_with(model: @article, local: true)  do |f| %>

  <p> 
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </p>

  <p>
    <%= f.submit %>

  </p>


<% end %>

app/views/articles/edit.html.erb
<h1> Edit article</h1>

<%= render 'form' %>

<p><%= link_to "cancel and return to articles listing", articles_path %></p>

app/views/articles/index.html.erb
<h1>Articles listing page</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Created by</th>
      <th>Description</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.user.username if article.user %> </td>
      <td><%= article.description %></td>
      <td><%= link_to "Show", article_path(article) %></td>
      <td><%= link_to "Delete", article_path(article), method: :delete,data: { confirm: "Are you sure?"} %></td>
      <td><%= link_to "Edit", edit_article_path(article) %> </td>
    </tr>
    <% end %>
  </tbody>
</table>

<p><%= link_to "Create new article", new_article_path %></p>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>

<p><%= link_to "Return to articles listing", articles_path %></p>

app/views/articles/show.html.erb
<h1>Show aritcle details</h1>

<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description %></p>

<%= link_to "Edit", edit_article_path(@article) %> |
<%= link_to "Delete", article_path(@article), method: :delete, data: { confirm: "Are you sure?"} %> |
<%= link_to "Return to articles listing", articles_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
  <%= msg %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" id="logo" href="#">Alpha Blog</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Dropdown
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Homework</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>

  <%
=begin%>
 <div class="container">
    <div class="card" style="width: 18rem;display: inline-block;">
      <div class="card-body">
        <h5 class="card-title">first blog</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Read more</a>
      </div>
    </div>
    <div class="card" style="width: 18rem;display: inline-block;">
      <div class="card-body">
        <h5 class="card-title">second blog</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Read more</a>
      </div>
    </div>
    <div class="card" style="width: 18rem;display: inline-block;">
      <div class="card-body">
        <h5 class="card-title">third blog</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="#" class="btn btn-primary">Read more</a>
      </div>
    </div>
  </div> 
<%
=end%>

    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>"Welcome to about page"</h1>

<%= link_to "articles listing", articles_path %> |
<%= link_to "Home page", root_path %>

app/views/pages/home.html.erb
<div id="page-content">
  <div class="container" id="home-container">
    <div class="jumbotron text-center">
      <h1 class="display-4">Alpha Blog</h1>
      <p class="lead">A place to make you feel better.</p>
      <hr class="my-4">
      <p>Write whatever your heart wants you to write.</p>
      <%= link_to "Sign up!", signup_path, class: "btn btn-success btn-lg" %>
    </div>
</div>

</div>


<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; Your Website</small>
  </div>
</footer>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <h2>The following errors prevented the <%= obj.class.name.downcase %> from being saved </h2>
  <% obj.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj:@user %>

<%= form_with(model: @user, local: true)  do |f| %>

  <p> 
    <%= f.label :username %><br>
    <%= f.text_field :username, placeholder: "Enter your username" %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.email_field :email, placeholder: "Enter your email" %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password, placeholder: "Enter your password" %>
  </p>

  <p>
    <%= f.submit(@user.new_record? ? "Sign up" : "Update account") %>

  </p>


<% end %>

app/views/users/edit.html.erb
<h1>Edit your profile</h1>

<%= render 'form' %>

<p><%= link_to "Return to articles listing", articles_path %></p>

app/views/users/new.html.erb
<h1>Sign up for alpha blog</h1>

<%= render 'form' %>

<p><%= link_to "Return to articles listing", articles_path %></p>